[tool.poetry]
name = "ada-final"
version = "0.1.0"
description = ""
authors = ["alexfriedman <alex.friedman@modo.energy>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
